export const storedProducts = [
  {
    id: 1,
    title: " Samsung Galaxy M31",
    img: require("./Component/Ecommerce/Images/Galaxy-M31s-DB-382x800-1595490916.jpg.webp"),
    price: 1200,
    company: " Samsung",
    info:
      "Samsung Galaxy M31s smartphone was launched on 30th July 2020. The phone comes with a 6.50-inch touchscreen display with a resolution of 1080x2400 pixels and an aspect ratio of 20:9. Samsung Galaxy M31s is powered by an octa-core Samsung Exynos 9611 processor. It comes with 6GB of RAM. The Samsung Galaxy M31s runs Android 10 and is powered by a 6000mAh non-removable battery. The Samsung Galaxy M31s supports proprietary fast charging.As far as the cameras are concerned, the Samsung Galaxy M31s on the rear packs a 64-megapixel primary camera with an f/1.8 aperture; a second 12-megapixel camera with an f/2.2 aperture; a third 5-megapixel camera with an f/2.4 aperture and a fourth 5-megapixel camera with an f/2.4 aperture. The rear camera setup has autofocus. It sports a 32-megapixel camera on the front for selfies, with an f/2.2 aperture.The Samsung Galaxy M31s runs One UI based on Android 10 and packs 128GB of inbuilt storage. The Samsung Galaxy M31s is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and Nano-SIM cards. It was launched in Mirage Black and Mirage Blue colours.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Samsung Galaxy Note 10 Lite",
    img: require("./Component/Ecommerce/Images/galaxy-note-10-lite-db-448x800.jpg.webp"),
    price: 2500,
    company: "Samsung",
    info:
      "The Samsung Galaxy S series and the Galaxy Note series smartphones have always been prime examples of what high-end Android smartphones are capable of. These devices are highly sought after and have always commanded a premium over what the other brands have on offer. Now, in order to compete better with brands such as OnePlus, and to lower the entry point for the Galaxy S and Galaxy Note series, Samsung has launched the Galaxy S10 Lite and Galaxy Note 10 Lite. These new smartphones are priced at around Rs. 40,000 which is significantly lower than their respective non-lite versions.",

    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: " Samsung Galaxy A70",
    img: require("./Component/Ecommerce/Images/a70front-377x800.jpg.webp"),
    price: 2100,
    company: "Samsung",
    info:
      "The Samsung Galaxy A70 is being marketed as a multimedia powerhouse that can also deliver good photography results with its triple rear cameras and offer a smooth performance. The Samsung phone packs a beautiful 6.7-inch full-HD+ (1080x2400 pixels) Super AMOLED display which is vibrant, has good viewing angles and great sunlight legibility, making it a great choice for watching videos and playing games.The phone is powered by the Snapdragon 675 processor paired with 6GB of RAM. The Galaxy A70 handles day-to-day tasks and gaming with ease, and the phone also does not heat up during intensive tasks. The Galaxy A70 also comes with Dolby Atmos support, but the in-display fingerprint sensor is a little slow at recognition.The triple rear cameras help the Galaxy A70 capture crisp photos with good edge details and decent dynamic range. However, the camera struggles to reproduce true colours under harsh daylight and there is also some softening at the periphery. But the phone lacks EIS and OIS support, but the slow-mo videos turned out very smooth. The Galaxy A70 packs a 4,500mAh battery which easily lasts through a full day of heavy usage, while the bundled Super Fast Charging adapter takes the battery from 0-100 in less than two hours.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Samsung Galaxy Z Flip ",
    img: require("./Component/Ecommerce/Images/samsung-galaxy-z-flip-373x800.jpg.webp"),
    price: 2200,
    company: "Samsung",
    info:
      "Samsung Galaxy Z Flip smartphone was launched on 20th February 2020. The phone comes with a 6.70-inch touchscreen primary display with a resolution of 1080x2636 pixels at a pixel density of 425 pixels per inch (ppi). It also features a 1.10-inch as its second display, with a resolution of 112x300 pixels at a pixel density of 303 pixels per inch (ppi),. Samsung Galaxy Z Flip is powered by a 2.95GHz octa-core Qualcomm Snapdragon 855+ processor. It comes with 8GB of RAM. The Samsung Galaxy Z Flip runs Android 10 and is powered by a 3300mAh battery. The Samsung Galaxy Z Flip supports wireless charging. The Samsung Galaxy Z Flip runs One UI 2.0 based on Android 10 and packs 256GB of inbuilt storage. The Samsung Galaxy Z Flip measures 167.30 x 73.60 x 7.20mm (height x width x thickness) and weighs 183.00 grams. It was launched in Mirror Black,Mirror Purple, and Mirror Gold colours. onnectivity options on the Samsung Galaxy Z Flip include Wi-Fi 802.11 a/b/g/n/ac, GPS, Bluetooth v5.00, and USB Type-C. Sensors on the phone include accelerometer, ambient light sensor, barometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor. The Samsung Galaxy Z Flip supports face unlock.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Samsung Galaxy J7 Prime ",
    img: require("./Component/Ecommerce/Images/samsung_galaxy_j7_prime.jpeg.webp"),
    price: 2400,
    company: "Samsung",
    info:
      "The new Samsung Galaxy J7 Prime has been launched at Rs. 18,790 and offers a lot of features. The 4G-enabled J7 Prime sports a metal body, full-HD display, massive battery, and some great software enhancements which make it one of the more interesting choices in the sub-Rs. 20,000 price category. On the downside, we wish that the camera performed a bit better in low light and the fingerprint scanner wasn’t so iffy.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Redmi Note 8",
    img: require("./Component/Ecommerce/Images/redmi-note-8.jpg.webp"),
    price: 3200,
    company: "Redmi",
    info:
      "The Redmi Note 8 should make smartphone buyers on a tight budget very happy. It doesn't look very slick, with a thick chin below its 6.3-inch screen, but you get a choice of gradients for the back, and there's a matching highlight colour around the bottom of the front face. The front and back are both Gorilla Glass 5, and there's an anti-splash coating which are both great for the budget segment. You get a Qualcomm Snapdragon 665 SoC with either 4GB of RAM and 64GB of storage, or 6GB of RAM and 128GB of storage. The full-HD+ resolution, 4000mAh battery and 48-megapixel main rear camera are also great features considering the price of this phone. Performance is very good, though gaming wasn't perfectly smooth. The cameras and battery life are good, but not spectacular. Overall, Xiaomi continues to offer excellent value for money.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Apple iPhone 7",
    img: require("./Component/Ecommerce/Images/iphone_7.jpeg.webp"),
    price: 2200,
    company: "Apple",
    info:
      "Apple iPhone 7 smartphone was launched in September 2016. The phone comes with a 4.70-inch touchscreen display with a resolution of 750x1334 pixels at a pixel density of 326 pixels per inch (ppi) and an aspect ratio of 16:9. Apple iPhone 7 is powered by a 2.34GHz quad-core Apple A10 Fusion processor. It comes with 2GB of RAM. The Apple iPhone 7 runs iOS 10 and is powered by a 1960mAh non-removable battery.As far as the cameras are concerned, the Apple iPhone 7 on the rear packs a 12-megapixel camera with an f/1.8 aperture. The rear camera setup has phase detection autofocus. It sports a 7-megapixel camera on the front for selfies, with an f/2.2 aperture.Apple iPhone 7 based on iOS 10 and packs 32GB of inbuilt storage. The Apple iPhone 7 is a single SIM (GSM) smartphone that accepts a Nano-SIM card. The Apple iPhone 7 measures 138.30 x 67.10 x 7.10mm (height x width x thickness) and weighs 138.00 grams. It was launched in Black, Gold, Jet Black, Matte Black, Red, Rose Gold, and Silver colours.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "iPhone 11 Pro",
    img: require("./Component/Ecommerce/Images/iphone-11-pro.jpg.webp"),
    price: 2500,
    company: "Apple",
    info:
      " iPhone 11 Pro smartphone was launched on 10th September 2019. The phone comes with a 5.80-inch touchscreen display with a resolution of 1125x2436 pixels at a pixel density of 458 pixels per inch (ppi). iPhone 11 Pro is powered by a hexa-core Apple A13 Bionic processor. It comes with 4GB of RAM. The iPhone 11 Pro runs iOS 13 and is powered by a 3046mAh non-removable battery. The iPhone 11 Pro supports wireless charging, as well as proprietary fast charging.iPhone 11 Pro based on iOS 13 and packs 64GB of inbuilt storage. The iPhone 11 Pro is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards. The iPhone 11 Pro measures 144.00 x 71.40 x 8.10mm (height x width x thickness) and weighs 188.00 grams. It was launched in Gold, Midnight Green, Silver, and Space Grey colours. It features an IP68 rating for dust and water protection. It bears a glass body. Connectivity options on the iPhone 11 Pro include Wi-Fi 802.11 a/b/g/n/ac/Yes, GPS, Bluetooth v5.00, NFC, Lightning, 3G, and 4G (with support for Band 40 used by some LTE networks in India). Sensors on the phone include accelerometer, ambient light sensor, barometer, gyroscope, proximity sensor, and compass/ magnetometer. The iPhone 11 Pro supports face unlock with 3D face recognition.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Huawei Mate 30 Pro ",
    img: require("./Component/Ecommerce/Images/huawei-mate-30-pro.jpg.webp"),
    price: 2500,
    company: "Huawei",
    info:
      "Huawei Mate 30 Pro smartphone was launched on 19th September 2019. The phone comes with a 6.53-inch touchscreen display with a resolution of 1176x2400 pixels. Huawei Mate 30 Pro is powered by a 1.86GHz octa-core HiSilicon Kirin 990 processor. It comes with 8GB of RAM. The Huawei Mate 30 Pro runs Android 10 and is powered by a 4500mAh battery. The Huawei Mate 30 Pro supports wireless charging, as well as proprietary fast charging.The Huawei Mate 30 Pro runs EMUI 10 based on Android 10 and packs 128GB of inbuilt storage (up to 256GB). The Huawei Mate 30 Pro is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and Nano-SIM cards. The Huawei Mate 30 Pro measures 158.10 x 73.10 x 8.80mm (height x width x thickness) and weighs 198.00 grams. It was launched in Space Silver, Emerald Green, Cosmic Purple, Black, Vegan Forest Green, and Vegan Orange colours.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Google Pixel 4 XL ",
    img: require("./Component/Ecommerce/Images/pixel-4.jpg.webp"),
    price: 2500,
    company: "Google",
    info:
      "Google Pixel 4 XL smartphone was launched on 15th October 2019. The phone comes with a 6.30-inch touchscreen display with a resolution of 1440x3040 pixels at a pixel density of 537 pixels per inch (ppi) and an aspect ratio of 19:9. Google Pixel 4 XL is powered by an octa-core Qualcomm Snapdragon 855 processor. It comes with 6GB of RAM. The Google Pixel 4 XL runs Android 10 and is powered by a 3700mAh non-removable battery. The Google Pixel 4 XL supports proprietary fast charging.As far as the cameras are concerned, the Google Pixel 4 XL on the rear packs a 16-megapixel primary camera with an f/2.4 aperture and a pixel size of 1.0-micron and a second 12.2-megapixel camera with an f/1.7 aperture and a pixel size of 1.4-micron. The rear camera setup has phase detection autofocus. It sports a 8-megapixel camera on the front for selfies, with an f/2.0 aperture and a pixel size of 1.22-micron.Google Pixel 4 XL based on Android 10 and packs 64GB of inbuilt storage. The Google Pixel 4 XL is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards. The Google Pixel 4 XL measures 160.40 x 75.10 x 8.20mm (height x width x thickness) and weighs 193.00 grams. It was launched in Just Black and Oh So Orange colours. It bears a glass body.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Samsung Galaxy S10e",
    img: require("./Component/Ecommerce/Images/samsung_galaxy_s10e.jpg.webp"),
    price: 2500,
    company: "Sumsang",
    info:
      "The Galaxy S10e is the smallest and lightest of the three new Galaxy S10 models at 150g. It feels incredibly comfortable to hold and the rounded edges aren't abrasive on the skin. The aluminium and glass back is a bit slippery when used with one hand, and this phone does attract fingerprints easily.The Samsung Galaxy S10e has a 5.8-inch full-HD+ Dynamic AMOLED display, with HDR 10+ certification. At the back of the phone, we noticed some more cutbacks compared to other Galaxy S10 models. It ditches the telephoto camera so you only get the main dual-aperture, 12-megapixel sensor and the 16-megapixel ultra-wide angle one.It has the Exynos 9820 octa-core SoC, alogn with 6GB of RAM and 128GB of storage. The Galaxy S10e also features AKG-tuned stereo speakers with Dolby Atmos, an IP68 certification for dust and water resistance, and a whole bunch of sensors.General app and UI performance is great. Games ran very well, even high-end ones such as PUBG Mobile. Thanks to the powerful SoC and lower screen resolution, the Galaxy S10e easily managed to drive them at the highest settings. The Galaxy S10e has a 3100mAh battery, which is the smallest of the series, and that has a noticeable effect in everyday use. We typically managed to get roughly 17 to 18 hours of actual battery life.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Realme Narzo 10A",
    img: require("./Component/Ecommerce/Images/realme-narzo.jpg.webp"),
    price: 2500,
    company: "Realme",
    info:
      "The Realme Narzo 10a is largely a cosmetic update to the Realme C3, which isn't a bad thing at all, as that model has performed very well in our tests. The Narzo 10a adds a fingerprint sensor, which takes care of one of our biggest complaints with the C3, as well as a macro camera on the rear, which is fun to use but not very practical. Performance is excellent thanks to the MediaTek Helio G70 processor, and you can get a decent enough gaming experience even with today's heavy games. The cameras are just about average, but quality dips a lot in low light. Battery life is excellent and we could get two full days of casual usage out of a single charge. This phone is available in So White and So Blue, with a gigantic Realme logo emblazoned across the back. Only one configuration is available, with 3GB of RAM and 32GB of storage.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
export const detailProduct = {
  id: 12,
  title: "Realme Narzo 10A",
  img: require("./Component/Ecommerce/Images/realme-narzo.jpg.webp"),
  price: 2500,
  company: "Realme",
  info:
    "The Realme Narzo 10a is largely a cosmetic update to the Realme C3, which isn't a bad thing at all, as that model has performed very well in our tests. The Narzo 10a adds a fingerprint sensor, which takes care of one of our biggest complaints with the C3, as well as a macro camera on the rear, which is fun to use but not very practical. Performance is excellent thanks to the MediaTek Helio G70 processor, and you can get a decent enough gaming experience even with today's heavy games. The cameras are just about average, but quality dips a lot in low light. Battery life is excellent and we could get two full days of casual usage out of a single charge. This phone is available in So White and So Blue, with a gigantic Realme logo emblazoned across the back. Only one configuration is available, with 3GB of RAM and 32GB of storage.",
  inCart: false,
  count: 0,
  total: 0,
};
